# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0b7b1c1b-7550-43ca-9040-ca874bcc84c3";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D189-0DA4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;


hardware.graphics = {
  enable = true;
  extraPackages = with pkgs; [
    intel-media-driver      # VA-API (iHD) userspace driver
    vpl-gpu-rt              # oneVPL (QSV) runtime
    intel-compute-runtime   # OpenCL (NEO) + Level Zero (optional)
  ];
};

hardware.amdgpu = {
  initrd.enable = true;   # Load driver early in boot
  opencl.enable = true;   # Enable OpenCL
};

}
