[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on = "+"
run = "plugin zoom 1"
desc = "Zoom in hovered file"

[[mgr.prepend_keymap]]
on = "-"
run = "plugin zoom -1"
desc = "Zoom out hovered file"


[[mgr.prepend_keymap]]
on = ["R", "b"]
run = "plugin recycle-bin"
desc = "Open Recycle Bin menu"


[[mgr.prepend_keymap]]
on = ["u"]
run = "plugin recycle-bin -- restore"
desc = "Restore last deleted file"


[[mgr.prepend_keymap]]
on = ["D"]
run = "plugin recycle-bin -- delete"
desc = "Permanently delete from recycle bin"


[[mgr.prepend_keymap]]
on = ["E"]
run = "plugin recycle-bin -- empty"
desc = "Permanently delete from recycle bin"


[[mgr.prepend_keymap]]
on = ["g", "t"]
run = "cd ~/.local/share/Trash/files"
desc = "Go to Trash"


[[mgr.prepend_keymap]]
on = ["g", "p"]
run = "cd ~/Projects"
desc = "Go to Projects"

[[mgr.prepend_keymap]]
on = ["g", "u"]
run = "cd /run/media/$USER"
desc = "Go to Media"


[[mgr.prepend_keymap]]
on = ["g", "v"]
run = "cd ~/Videos"
desc = "Go to Videos"


[[mgr.prepend_keymap]]
on = ["Y"]
run = '''
	shell --block --confirm '
		read -p "yt-dlp URL: " url
		if [ -n "$url" ]; then
			yt-dlp -o "%(title)s.%(ext)s" "$url"
		fi
	'
'''
desc = "Download video/audio with yt-dlp into current dir"


[[mgr.prepend_keymap]]
on = "T"
run = 'shell "clear; fish -C \"bind \e exit\"" --block'
desc = "Open shell here"
