# --- Eye Candy Visuals ---
# window_padding_width 2
# background_blur      1
background_opacity   0.7
confirm_os_window_close 0

# --- Cinematic Cursor ---
cursor_shape beam
cursor_beam_thickness 2

cursor_blink_interval 0.7
cursor_stop_blinking_after 15.0

# --- Exaggerated Follow / Motion Trail ---
cursor_trail 20
cursor_trail_decay 0.04 0.8
cursor_trail_start_threshold 1





# --- Tab Bar Aesthetics ---
tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted
active_tab_font_style   bold
inactive_tab_font_style normal




include themes/noctalia.conf


# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 13.0

map ctrl+h neighboring_window left
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+l neighboring_window right



# END_KITTY_FONTS
