source = ~/.config/mango/conf.d/autostart.conf
source = ~/.config/mango/conf.d/appearance.conf
source = ~/.config/mango/conf.d/animations.conf
source = ~/.config/mango/conf.d/input.conf
source = ~/.config/mango/conf.d/layout.conf
source = ~/.config/mango/conf.d/rules.conf
source = ~/.config/mango/conf.d/binds.conf
source = ~/.config/mango/conf.d/monitors.conf

# This sources the noctalia theme

source=~/.config/mango/noctalia.conf
